---
title: "saycam bb outputs compile"
author: "Bria Long"
date: "1/9/2020"
output: html_document
---

# Basic data loading and setup
## Packages
```{r setup, include=FALSE}
 knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(tidyverse)
library(assertthat)
library(ggthemes)
library(lme4)
library(langcog)
library(viridis)
library(magick)
library(stringr)
library(lubridate)
library(egg)
library(here)
theme_set(theme_few())
## are we saving outputs
saveFiles = TRUE
```

```{r}
op_file_dir = "../data/op_outputs_per_vid/"
op_files = dir(op_file_dir)
```

```{r}
vid_index = 0
for (vid_file in op_files) {
  vid_index = vid_index + 1
   vid_file_path = paste0(here::here(), '/data/op_outputs_per_vid/', vid_file)
   this_vid_data <- readRDS(vid_file_path)
   summary_vid_data <- this_vid_data %>%
     group_by(frame, child_id, vid_name, right_side_up, age_days) %>%
     summarize(hand_detected = sum(!is.na(mean_confidence[label=='hand']))>0,face_detected = sum(!is.na(mean_confidence[label=='face']))>0)  %>%
     group_by(child_id, vid_name, right_side_up, age_days) %>%
     summarize(prop_hands = mean(hand_detected), prop_faces = mean(face_detected), num_detect = length(hand_detected))
   
   if (vid_index == 1 ){
     all_vid_data <- summary_vid_data
   }
   else if (vid_index > 1) {
   all_vid_data <- all_vid_data %>%
     full_join(summary_vid_data)
   }
}
```

```{r}
### Choose bins across which to analyze data
bin_size = 7 # days
min_age = min(all_vid_data$age_days, na.rm=TRUE)
max_age = max(all_vid_data$age_days, na.rm=TRUE)
bin_starts = seq(min_age-1, max_age+1,bin_size)
bins = c(bin_starts, max_age)
```


## regualrize vid names
```{r}
all_vid_data <- all_vid_data %>%
  rowwise() %>%
  mutate(vid_name_cleaned = str_split(vid_name,"[.]")[[1]][1])
```

## filter allocentric videos
```{r}
allocentric_file = "../data/raw_data/SAYCAM_allocentric_videos.csv"
to_exclude =read.csv(allocentric_file)

# get INCORRECT videos 
to_exclude <- to_exclude %>%
  filter(allocentric==1) %>%
  rename(vid_name = video)
```

## get rid of vids to exclude
```{r}
all_vid_data <- all_vid_data %>%
  mutate(vid_name_old = vid_name) %>%
  select(-vid_name) %>%
  filter(!vid_name_cleaned %in% to_exclude$vid_name)
```

```{r}
missing_age <-all_vid_data %>%
  filter(is.na(age_days))
```

## summarize by age
```{r}
summary_by_age <- all_vid_data %>%
  filter(!is.na(age_days)) %>%
  mutate(age_day_bin = cut(age_days, bins, labels=round(bin_starts/30,1))) %>%
  mutate(age_day_bin = as.numeric(as.character(age_day_bin))) %>%
  group_by(age_day_bin, child_id) %>%
  summarize(num_frames_total = sum(num_detect), num_faces = sum(prop_faces*num_detect), num_hands = sum(prop_hands*num_detect), prop_faces_summary = num_faces / num_frames_total, prop_hands_summary = num_hands / num_frames_total)

```

```{R}
wide_uncropped <- summary_by_age %>%
  gather(region, prop, prop_faces_summary, prop_hands_summary) %>%
  mutate(approach = "uncropped",
         region = ifelse(region == "prop_faces_summary","Face","Hands"))  %>%
  filter(num_frames_total > 5000) # eliminate one data point that skews scaling 
```

```{r}
ggplot(wide_uncropped,
       aes(x=age_day_bin, y=prop,
           size=log10(num_frames_total),
           col=region)) +
  geom_point(alpha=.2) +
  geom_smooth(span=10, aes(weight = num_frames_total), show.legend = FALSE) + # geom_smooth(show.legend = FALSE) or move these below legend?
  # geom_smooth(data = wide_center, aes(weight = num_detect), show.legend = FALSE,
  #             lty = 2, span=10, se = FALSE) +
  # # geom_smooth(data = wide_gold, aes(weight = num_detect), show.legend = FALSE,
  #             lty = 3, span=10, se = FALSE) +
  ylab('Proportion Detections') +
  xlab('Age (Months)') +
  ylim(0,.5) +
  facet_grid(.~child_id) +
  theme_few(base_size=18) +
  ggthemes::scale_color_solarized(name = "") +
  scale_size_continuous(name = "Detections (Log 10)") +
  theme(legend.text=element_text(size=8)) +
  theme(legend.position="bottom")
```



```{r}
faces_model_out= summary(lmer(prop_faces_summary ~ scale(age_day_bin) + (1 | child_id), data = summary_by_age))

hands_model_out= summary(lmer(prop_hands_summary ~ scale(age_day_bin) + (1 | child_id), data = summary_by_age))

```


```{r}
load(here('data_cogsci/saycam_metadata.RData'))

num_videos_annotated = sum(!is.na(meta$Location))
videos_included = sum(!is.na(meta$Location) & meta$count_locations==1)

# percentage_of_dataset = sum(faces_vs_hands_to_plot$num_detect)/length(d_all$frame)
# num_frames = sum(faces_by_location_to_plot$num_detect)
```

