---
title: "Preprocess turk annotations (hand/face detection)"
output: html_notebook
---


```{r setup, echo = FALSE}
library(knitr)
opts_chunk$set(echo = TRUE)
library(tidyverse)
library(assertthat)
library(ggthemes)
library(lme4)
library(langcog)
library(lmerTest)
library(viridis)
library(magick)
library(here)
library(lubridate)
library(egg)
theme_set(theme_few())
```

# Preprocessing
```{r}
jf <- paste0(here::here(), '/data/turk_data/raw/face_hand_detections/Batch_3858789_batch_results.csv')

jd <- read_csv(jf)

summary <- jd %>%
  group_by(WorkerId) %>%
  summarize(avg_time = mean(WorkTimeInSeconds))

```

### Go through raw data and put in dataframe
```{r}
d.raw <- data.frame()
trial_indexes = seq(1,252,1)
num_workers=20
d <- read_csv(jf)
  
## really not sure why there's this weird discrepancy for the last trial, but OK
jd$`Answer.trial-252` = jd$`Answer.trial-252.label`
  
for (trial_ind in trial_indexes){
    trial_data = data.frame(
      ## including HITId and HITTYpe
      this_response = eval(parse(text = paste0("jd$`Answer.trial-",trial_ind,"`"))),
      full_image_path = eval(parse(text = paste0("jd$Input.img_src",trial_ind))),
      trial_number = trial_ind,
      HITID = jd$HITId,
      HITTypeId =jd$HITTypeId,
      WorkerID = jd$WorkerId
    )
    d.raw <- bind_rows(d.raw, trial_data)
}

d <- d.raw

## Would like to get rando responses in .label field here:
### Sometimes we get NAs and they end up in ".label fields", but not every trial has them (so it throws errors in a loop). I'm too tired to write an appropriate function so just leaving those NAs for now but the data is there. Starter code is below.
# empty_labels = as.character(array(matrix(data=NA, nrow=1, ncol=num_workers)))
# 
# 
# for (trial_ind in trial_indexes){
#   field_to_check = paste0("jd$`Answer.trial-",trial_ind,".label`")
#   if (!field_to_check %in% colnames(jd)){
#     jd$(field_to_check) = empty_labels
#   }
# }

# na_indexes = is.na(d$this_response)
# d$this_response[na_indexes] = d$this_response_label[na_indexes]
```

### Write function to spit back category of sanity check images
```{r message=FALSE}
sanity_check_category = function(shorter_image_path){
 ## I hate this function but I couldn't make it work without 
## going down a regex rabbithole so here it is
  hands = str_detect(shorter_image_path,'hands')
  faces = str_detect(shorter_image_path,'face')
  none = str_detect(shorter_image_path,'none')
  both = str_detect(shorter_image_path,'face-hands')

 if (both==TRUE){
   category = 'both'
 }
 else if (hands==TRUE){
   category = 'hands'
 }
 else if (faces==TRUE){
   category='faces'
 }
 else if (none==TRUE){
  category='none'   
 }
 else{
   category=NA
  }
 
 return(category)
}
```


### Pop out sanity check category from image path
```{r}
d <- d %>%
    mutate(short_image_path = str_split_fixed(full_image_path,'/',7)[,7]) %>%
    mutate(shorter_image_path = str_split_fixed(short_image_path,'.jpg',2)[,1]) %>%
    rowwise() %>%
    mutate(sanity_check_category = sanity_check_category(shorter_image_path))
```

### Recode responses into easier to munge format
```{r}
level_key <- c("Face(s) and Hand(s)" = "both", "Hand(s) only" = "hands", "Neither face(s) nor hands(s)" = "none", "Face(s) only" = "faces")

d$response=array()
d$response <- recode(d$this_response, !!!level_key)

get_face_hands =function(this_response,which_type){
  if (is.na(this_response)){
    face=NA
    hand=NA
  }
  else if (this_response=='both'){
    face=TRUE
    hand=TRUE
  }
  else if (this_response=='faces'){
    face=TRUE
    hand=FALSE
  }
  else if (this_response=='hands'){
    face=FALSE
    hand=TRUE
  }
  else if (this_response=='none'){
    face=FALSE
    hand=FALSE
  }
  else {
    face=NA
    hand=NA
  }
  
  if (which_type=='faces'){
    return(face)
  }
  else if (which_type=='hands'){
    return(hand)
  }
}

d <- d %>%
  mutate(hands= get_face_hands(response,'hands'), faces = get_face_hands(response,'faces')) %>%
  mutate(sanity_hands = get_face_hands(sanity_check_category,'hands'), sanity_faces = get_face_hands(sanity_check_category,'faces'))
```

### Break out sanity check images and filter ad workers
```{r}
sanity_images_wrong <- d %>%
  filter(!is.na(sanity_check_category)) %>%
  mutate(correct_sanity = response == sanity_check_category) %>%
  mutate(correct_faces = (faces == sanity_hands), correct_hands = (hands == sanity_hands)) %>%
  filter(correct_sanity == FALSE) 

bad_workers <- sanity_images_wrong %>%
  group_by(WorkerID) %>%
  summarize(wrong_sanity = n()) %>%
  filter(wrong_sanity > 3) # more than 1/4 wrong

d.filtered <- d %>%
  filter(!WorkerID %in% bad_workers$WorkerID)
```

### Write out csv for use in analysis
```{r}
write_csv(d.filtered,paste0(here::here, '/data/turk_data/face_hand_detections', today(), '.csv'))
```


```{r}
## Compute agreement -- not using since only 1 worker per set right now
# agreement <- d.raw %>%
#   group_by(short_image_path, full_image_path) %>%
#   summarize(workers_per_image = length(this_response), num_responses = length(unique(this_response)), face_agree = (faces[1] == faces[2]), hand_agree = (hands[1]==hands[2]))
# 
# disagreement_examples <- agreement %>%
#   filter(workers_per_image==2) 

# for (i in length(disagreement_examples$full_image_path)){
#   brxowseURL(disagreement_examples$full_image_path[i])
# }

# percent_disagree = sum(agreement$num_responses==2) / length(agreement$num_responses)

# dir.create(paste0('disagreements_take2/'))
# for (i in seq(1,length(disagreement_examples$full_image_path),1)){
#   image_read(disagreement_examples$full_image_path[i]) %>%
#   image_append(stack = FALSE) %>%
#   image_write(file.path(paste0("disagreements_take2/", disagreement_examples$short_image_path[i])))
# }

# example <- d.raw %>%
#   filter(short_image_path == "582-A_20130612_0830_02.mp4-2370.jpg")
```

