---
title: "Generate annotation frames"
author: "Bria Long"
date: "1/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(tidyverse)
library(assertthat)
library(ggthemes)
library(lme4)
library(langcog)
library(viridis)
library(magick)
library(stringr)
library(egg)
theme_set(theme_few())
```


### Instead load in detections and ketan's gold set annotations from preprocessed Rdata files
```{r}
load('../data/raw_data/ketan_gold_sample.RData')
```

### Load file to filter flipped videos (when sam's mom was wearing camera; not egocentric)
```{r}
right_side_up_file = "../data/video_right-side-up.csv"
right_side_up =read.csv(right_side_up_file)

# get INCORRECT videos
flipped_videos <- right_side_up %>%
  filter(right_side_up==1)
```


### Get out frame urls for frames where ketan annotated hands
```{r}
## preprocess all frame urls
frame_urls = "../data/frame_urls.csv"
gold_frame_urls =read.csv(frame_urls) %>%
    as_tibble() %>%
    mutate(short_image_path = str_split_fixed(img_src1,'/',7)[,7]) %>%
    mutate(sample_ind = str_split_fixed(short_image_path,"-",3)[,1], frame_ind_temp = str_split_fixed(short_image_path,"-",3)[,3], vid_name = str_split_fixed(short_image_path,"-",3)[,2]) %>%
  mutate(sample_ind = as.numeric(sample_ind), frame_ind = as.numeric(str_split_fixed(frame_ind_temp,".jpg",3)[,1])) %>%
  mutate(vid_name_short = str_split_fixed(vid_name,".mp4",2)[,1]) %>%
  select(vid_name, frame_ind, short_image_path, img_src1) %>%
  rename(frame=frame_ind) %>%
  mutate(vid_name = as.character(vid_name)) 

## grab frames were hands were present
hand_present_frames <- ketan_gold %>%
  filter(hand_present==1) %>%
  select(vid_name,frame) %>%
  rowwise() %>%
  mutate(vid_name_short = str_split(vid_name,"[.]")[[1]][1]) %>%
  filter(!vid_name_short %in% flipped_videos$video) %>%
  mutate(vid_name = as.character(vid_name)) %>%
  left_join(gold_frame_urls)


## write out to csv
hand_present_filepaths <- hand_present_frames %>%
  select(img_src1) 

write_csv(hand_present_filepaths,'../data/hands_present_goldset.csv')

# render out some of these...
# dir.create(paste0('hands_present/'))
# for (i in seq(1,length(hand_present_frames$img_src1),1)){
#   image_read(as.character(hand_present_frames$img_src1[i])) %>%
#   image_append(stack = FALSE) %>%
#   image_write(file.path(paste0("hands_present/", hand_present_frames$short_image_path[i])))
# }

```